mutation CreatePublicList($name: String!, $description: String!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  list_insert(data: {
    name: $name,
    description: $description,
    public: true,
    createdAt_expr: "request.time",
    updatedAt_expr: "request.time",
    userId_expr: "uuidV4()" #  IN_PROD: userId_expr: "auth.uid"
  })
}

query GetMyLists @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  lists(where: { userId: { eq_expr: "auth.uid" } }) {
    id
    name
    description
    public
    createdAt
    updatedAt
  }
}

mutation AddMovieToList($listId: UUID!, $movieId: UUID!, $position: Int!) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  listMovie_insert(data: {
    listId: $listId,
    movieId: $movieId,
    position: $position
  })
}

mutation CreateReview($movieId: UUID!, $rating: Int!, $review: String!) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  review_insert(data: {
    movieId: $movieId,
    userId_expr: "auth.uid",
    watchId_expr: "uuidV4()", # IN_PROD: The Watch table does not exists, remove it.
    rating: $rating,
    review: $review,
    createdAt_expr: "request.time",
    updatedAt_expr: "request.time"
  })
}